import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { AlertCircle, ArrowLeft, Download, ShieldCheck, HeartPulse, Info, FileText } from 'lucide-react';
import '../styles/theme.css';

const ResultDashboard = () => {
  const { state } = useLocation();
  const navigate = useNavigate();

  if (!state) {
    return <div className="p-10 text-center">No data found. <button onClick={() => navigate('/chat')} className="btn-primary-small">Go Back</button></div>;
  }

  const { consultation_id, triage, conditions, next_steps, color_code, symptoms_input, explanation } = state;

  const handleDownloadPDF = () => {
    const token = localStorage.getItem('auth_token');
    window.open(`http://localhost:8000/api/report/${consultation_id}?token=${token}`, '_blank');
  };

  return (
    <div className="results-container">
      <header className="results-header">
        <button onClick={() => navigate('/chat')} className="back-btn"><ArrowLeft size={18} /> Back to Chat</button>
        <div className="res-title">
          <h2>Health Assessment Result</h2>
          <span className="res-id">Report ID: #A-{consultation_id}</span>
        </div>
        <button className="btn-export" onClick={handleDownloadPDF}>
          <Download size={18} /> <span>Export PDF</span>
        </button>
      </header>

      <main className="results-grid">

        {/* 2. AI ANALYSIS EXPLANATION */}
        <div className="card full-width analysis-card">
          <div className="card-header">
            <Info size={20} className="icon-blue" />
            <h3>ArogyaAI Clinical Insight</h3>
          </div>
          <div className="explanation-body">
            {explanation || "Our AI has analyzed your symptoms based on clinical patterns and decision rules."}
          </div>
        </div>

        {/* 3. SYMPTOMS */}
        <div className="card">
          <div className="card-header">
            <HeartPulse size={20} className="icon-red" />
            <h3>Symptoms Identified</h3>
          </div>
          <div className="symptom-tags">
            {symptoms_input?.map((s, i) => (
              <span key={i} className="s-tag">{s}</span>
            ))}
          </div>
        </div>

      </main>

      <footer className="medical-disclaimer-box">
        <AlertCircle size={20} />
        <p>
          <strong>Clinical Disclaimer:</strong> This assessment is generated by an AI system for informational purposes. It is not a substitute for a professional medical diagnosis, advice, or treatment. 
          If you are experiencing severe symptoms, please visit the emergency room immediately.
        </p>
      </footer>

      <style jsx>{`
        .results-container {
          max-width: 900px;
          margin: 0 auto;
          padding: 60px 20px;
          color: #000000;
        }
        
        .results-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 40px;
        }

        .back-btn {
          display: flex;
          align-items: center;
          gap: 8px;
          background: none;
          border: none;
          color: #64748b;
          font-weight: 700;
          cursor: pointer;
        }

        .res-title { text-align: center; }
        .res-title h2 { margin: 0; font-size: 1.5rem; font-weight: 800; }
        .res-id { font-size: 0.75rem; color: #94a3b8; font-weight: 700; }

        .btn-export {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 20px;
          background: #f1f5f9;
          border: none;
          border-radius: 100px;
          font-weight: 700;
          cursor: pointer;
          transition: 0.2s;
        }
        .btn-export:hover { background: #e2e8f0; }

        .results-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 24px;
        }

        .full-width { grid-column: span 2; }

        /* TRIAGE CARD */
        .triage-card-large {
          grid-column: span 2;
          padding: 40px;
          border-radius: 24px;
          display: flex;
          align-items: center;
          gap: 40px;
          background: #ffffff;
          border: 1px solid #e5e7eb;
        }
        .triage-card-large.red { border-left: 8px solid #ef4444; background: #fffafb; }
        .triage-card-large.yellow { border-left: 8px solid #f59e0b; background: #fffbeb; }
        .triage-card-large.green { border-left: 8px solid #10b981; background: #f0fdf4; }

        .triage-visual {
          width: 80px;
          height: 80px;
          background: #f1f5f9;
          border-radius: 20px;
          display: flex;
          align-items: center;
          justify-content: center;
          color: #2563eb;
          position: relative;
        }
        .red .triage-visual { color: #ef4444; }

        .triage-info h1 { font-size: 2.5rem; font-weight: 900; margin: 0 0 8px; }
        .label-mini { font-size: 0.75rem; font-weight: 800; text-transform: uppercase; color: #64748b; }
        .triage-info p { font-size: 1.1rem; font-weight: 600; opacity: 0.8; margin: 0; }

        .card {
          background: #ffffff;
          padding: 30px;
          border-radius: 20px;
          border: 1px solid #e5e7eb;
        }
        .card-header { display: flex; align-items: center; gap: 12px; margin-bottom: 20px; }
        .card-header h3 { font-size: 1.1rem; font-weight: 800; margin: 0; }

        .explanation-body { font-size: 1.1rem; line-height: 1.7; color: #334155; }

        .symptom-tags { display: flex; flex-wrap: wrap; gap: 10px; }
        .s-tag { padding: 8px 16px; background: #f1f5f9; border-radius: 100px; font-weight: 700; font-size: 0.9rem; }

        .cond-row { margin-bottom: 20px; }
        .cond-meta { display: flex; justify-content: space-between; margin-bottom: 8px; font-weight: 800; font-size: 0.95rem; }
        .c-bar-bg { height: 8px; background: #f1f5f9; border-radius: 4px; }
        .c-bar-fill { height: 100%; background: #2563eb; border-radius: 4px; }

        .medical-disclaimer-box {
          margin-top: 50px;
          padding: 24px;
          background: #f8fafc;
          border-radius: 16px;
          display: flex;
          gap: 16px;
          color: #64748b;
          font-size: 0.9rem;
          line-height: 1.6;
        }

        .icon-blue { color: #2563eb; }
        .icon-red { color: #ef4444; }
        .icon-teal { color: #0d9488; }

        @media (max-width: 768px) {
          .results-grid { grid-template-columns: 1fr; }
          .triage-card-large { flex-direction: column; text-align: center; gap: 20px; }
          .full-width, .card { grid-column: span 1; }
        }
      `}</style>
    </div>
  );
};

export default ResultDashboard;
