<!DOCTYPE html>
<html>
<head>
    <title>ArogyaAI Medical Triage Report</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 28px; font-weight: bold; color: #2563eb; }
        .triage-badge { 
            display: inline-block; 
            padding: 10px 20px; 
            border-radius: 5px; 
            color: white; 
            font-weight: bold; 
            margin-bottom: 20px;
        }
        .emergency { background-color: #ef4444; }
        .primarycare { background-color: #f59e0b; }
        .selfcare { background-color: #10b981; }
        .section { margin-bottom: 25px; }
        .section-title { font-size: 18px; font-weight: bold; margin-bottom: 10px; color: #1e293b; }
        .symptom-list { margin-left: 20px; }
        .condition-item { margin-bottom: 10px; padding: 10px; background: #f8fafc; border-radius: 5px; }
        .disclaimer { font-size: 12px; font-style: italic; color: #64748b; margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 10px; }
        .user-info { margin-bottom: 20px; font-size: 14px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">ArogyaAI</div>
        <p>Intelligent Health Triage Report</p>
    </div>

    <div class="user-info">
        <strong>Patient:</strong> {{ $user->name }}<br>
        <strong>Email:</strong> {{ $user->email }}<br>
        <strong>Date:</strong> {{ $consultation->created_at->format('M d, Y H:i') }}
    </div>

    <div class="section">
        <div class="triage-badge {{ strtolower(str_replace('_', '', $triage)) }}">
            TRIAGE LEVEL: {{ str_replace('_', ' ', $triage) }}
        </div>
    </div>

    <div class="section">
        <div class="section-title">Extracted Symptoms</div>
        <ul class="symptom-list">
            @foreach($symptoms as $symptom)
                <li>{{ ucfirst($symptom) }}</li>
            @endforeach
        </ul>
    </div>

    <div class="section">
        <div class="section-title">Possible Conditions</div>
        @foreach($predictions as $prediction)
            <div class="condition-item">
                <strong>{{ $prediction->condition_name }}</strong> - Probability: {{ $prediction->probability * 100 }}%
            </div>
        @endforeach
    </div>

    <div class="disclaimer">
        IMPORTANT: This report is generated by an AI system for informational purposes only. This is not a medical diagnosis. Always consult a licensed medical professional for health concerns.
    </div>
</body>
</html>
